language: node_js
node_js:
  - "10"
cache: 
  npm: false

notifications:
  email:
    recipients:
      - lorance7016@163.com # 设置通知邮件
    on_success: change
    on_failure: always

before_install:
  - npm i -g npm@latest

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - cd _book
  - echo "gitbook.scalachan.com" >> CNAME
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" master:master

branches:
  only:
    - master

env:
  global:
    - REF=github.com/lorancechen/lorancechen.github.io.git # 设置 github 地址
